version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34.10
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: ec2-52-1-95-247.compute-1.amazonaws.com
            port: 5432
            database: d2bmad6kbpnh3k
            ssl: true
            user: nresrcxbpltawz
            password: 0d31c4faecd81cc9bb735f5fad5ce5f223b3318fcd7cebb8cf556aae9aead8a7
            migrations: true